{
 "title": "DUAL ISP INTERNET MONITORING",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ISP_A Traffic Percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_A\"}[5m]) * 8) / 200e6 * 100",
     "legendFormat": "Downstream Traffic Percentage"
    },
    {
     "expr": "(rate(ifHCOutOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_A\"}[5m]) * 8) / 200e6 * 100",
     "legendFormat": "Upstream Traffic Percentage"
    }
   ]
  },
  {
   "title": "ISP_B Internet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(probe_success{job=\"blackbox_isp_b\"})\r\n* on()\r\n(ifOperStatus{instance=\"firewall.example.internal\", ifName=\"INTERFACE_B\"} == bool 1)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ISP_B Traffic Percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_B\"}[5m]) * 8) / 200e6 * 100",
     "legendFormat": "Downstream Traffic Percentage"
    },
    {
     "expr": "(rate(ifHCOutOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_B\"}[5m]) * 8) / 200e6 * 100",
     "legendFormat": "Upstream Traffic Percentage"
    }
   ]
  },
  {
   "title": "ISP_A Internet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(probe_success{job=\"blackbox_isp_a\"})\r\n* on()\r\n(ifOperStatus{instance=\"firewall.example.internal\", ifName=\"INTERFACE_A\"} == bool 1)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ISP_A Download Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_A\"}[5m]) * 8 / 1e6",
     "legendFormat": "ISP_A Download"
    }
   ]
  },
  {
   "title": "ISP_A Upload Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_A\"}[5m]) * 8 / 1e6",
     "legendFormat": "ISP_A Upload"
    }
   ]
  },
  {
   "title": "ISP_B Download Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_B\"}[5m]) * 8 / 1e6",
     "legendFormat": "ISP_B Download"
    }
   ]
  },
  {
   "title": "ISP_B Upload Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"snmp_firewall\", instance=\"firewall.example.internal\", ifName=\"INTERFACE_B\"}[5m]) * 8 / 1e6",
     "legendFormat": "ISP_B Upload"
    }
   ]
  }
 ]
}